version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis

  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "6379:6379"